import {MatButtonModule, MatCheckboxModule, MatToolbarModule,
        MatListModule, MatDividerModule, MatRippleModule, MatTableModule,
        MatSortModule,
        MatFormFieldModule,
        MatInputModule,
        MatCardModule,
        MatSelectModule,
        MatDatepickerModule,
        MatSnackBarModule,
        MatIconModule,
        MatMenuModule,
        MatDialogModule,
        MatTooltipModule,
        MatExpansionModule} from '@angular/material';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

@NgModule({
  imports: [MatButtonModule,
            MatCheckboxModule,
            MatToolbarModule,
            MatListModule,
            MatDividerModule,
            MatRippleModule,
            MatTableModule,
            MatSortModule,
            MatFormFieldModule,
            MatInputModule,
            MatCardModule,
            FormsModule,
            MatSelectModule,
            MatDatepickerModule,
            MatSnackBarModule,
            MatIconModule,
            MatMenuModule,
            MatDialogModule,
            MatTooltipModule,
            MatExpansionModule],
  exports: [MatButtonModule,
            MatCheckboxModule,
            MatToolbarModule,
            MatListModule,
            MatDividerModule,
            MatRippleModule,
            MatTableModule,
            MatSortModule,
            MatFormFieldModule,
            MatInputModule,
            MatCardModule,
            FormsModule,
            MatSelectModule,
            MatDatepickerModule,
            MatSnackBarModule,
            MatIconModule,
            MatMenuModule,
            MatDialogModule,
            MatTooltipModule,
            MatExpansionModule],
})
export class MaterialConstrolsModule { }
